# web port
server:
  port: 8081

# log config
logging:
  config: classpath:logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://localhost:8080/

    ### xxl-job executor address
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 9999
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1

    ### xxl-job, access token
    accessToken:


